CREATE TABLE CLIENTE(CLIENTE_ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
CLIENTE_NOME VARCHAR(50),
CLIENTE_SOBRENOME VARCHAR(50), 
CLIENTE_SEXO CHAR(1),	              
CLIENTE_END VARCHAR(50),
CLIENTE_END_CIDADE CHAR(20),
ESTADO_CODIGO VARCHAR(2),
CLIENTE_END_CEP VARCHAR(10),
CLIENTE_NASC DATE,
CLIENTE_TELEFONE VARCHAR(14),
CLIENTE_PERC_DESCONTO DECIMAL (2,0),   
CLIENTE_NUM_END VARCHAR(6),
CLIENTE_EMAIL VARCHAR(50)
);

CREATE TABLE ESTADO(
ESTADO_CODIGO VARCHAR(2),
ESTADO_NOME VARCHAR(25)
);

CREATE TABLE PRODUTO(
PRODUTO_CODIGO SMALLINT,
PRODUTO_NOME VARCHAR(40),
PRODUTO_PRECO NUMERIC(5,2),
UE_PRODUTO_COD VARCHAR(3)
);

CREATE TABLE PEDIDO(
PEDIDO_IDENTIFICACAO INTEGER,
PEDIDO_TIPO INTEGER,
CLIENTE_ID INTEGER,
PEDIDO_DATA_ENTRADA DATE,
PEDIDO_VALOR_TOTAL NUMERIC(7,2),
PEDIDO_DESCONTO NUMERIC(7,2),
PEDIDO_DT_EMBARQUE DATE
);

CREATE TABLE UE_PRODUTO(
UE_PRODUTO_COD CHAR(3),
UE_PRODUTO_DESCR VARCHAR(50)
);

CREATE TABLE ITEM(
PEDIDO_IDENTIFICACAO INTEGER,
PRODUTO_CODIGO SMALLINT,
ITEM_QUANTIDADE SMALLINT,
ITEM_VALOR_UNITARIO NUMERIC(5,2),
ITEM_VALOR_TOTAL NUMERIC(5,2)
);

ALTER TABLE CLIENTE
ADD CONSTRAINT cliente_pkey  PRIMARY KEY (CLIENTE_ID);

ALTER TABLE ESTADO
ADD CONSTRAINT estado_pkey PRIMARY KEY (ESTADO_CODIGO);

ALTER TABLE ITEM
ADD CONSTRAINT item_pkey PRIMARY KEY (PEDIDO_IDENTIFICACAO,PRODUTO_CODIGO);

ALTER TABLE PEDIDO
ADD CONSTRAINT pedido_pkey PRIMARY KEY (PEDIDO_IDENTIFICACAO);

ALTER TABLE PRODUTO
ADD CONSTRAINT produto_pkey PRIMARY KEY (PRODUTO_CODIGO);

ALTER TABLE UE_PRODUTO
ADD CONSTRAINT ue_produto_pkey PRIMARY KEY (UE_PRODUTO_COD);

ALTER TABLE CLIENTE
ADD CONSTRAINT cliente_estado_fk FOREIGN KEY (ESTADO_CODIGO)
REFERENCES ESTADO(ESTADO_CODIGO);

ALTER TABLE PEDIDO
ADD CONSTRAINT pedido_cliente_fk FOREIGN KEY (CLIENTE_ID)
REFERENCES CLIENTE(CLIENTE_ID);

ALTER TABLE PRODUTO
ADD CONSTRAINT produto_ueproduto_fk FOREIGN KEY (UE_PRODUTO_COD)
REFERENCES UE_PRODUTO(UE_PRODUTO_COD);

ALTER TABLE ITEM
ADD CONSTRAINT item_produto_fk FOREIGN KEY (PRODUTO_CODIGO)
REFERENCES PRODUTO(PRODUTO_CODIGO);

